### ISSUE TITLE
Add boot from USB Stick option

### ISSUE THREAD

**Issue by BillMeyerRSA** [minkebox/minke#1]
I found that working with the SD Card on Raspberry Pi can sometimes damage the SD Card. (Not related to Minke, just in general, removing re-flashing etc and then snap!)

Is it possible to add the Boot from USB storage option? Easier when experimenting with software to flash to a USB stick and plug in. 
https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md

**Comment by aanon4** [comment]
Reading about booting on the Raspberry Pi 3B+, it seems to suggest that it would boot of a USB drive without changes. So .. maybe .. flashing the MinkeBox code into a flash drive and plugging it in will "just work"? Have you tried?
